apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: microservices
build:
  artifacts:
    - image: yinglu91/m-client
      context: client
      docker:
        dockerfile: Dockerfile
    - image: yinglu91/m-comments
      context: comments
      docker:
        dockerfile: Dockerfile
    - image: yinglu91/m-event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
    - image: yinglu91/m-moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
    - image: yinglu91/m-posts
      context: posts
      docker:
        dockerfile: Dockerfile
    - image: yinglu91/m-query
      context: query
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - infra/k8s/client-depl.yaml
      - infra/k8s/comments-depl.yaml
      - infra/k8s/event-bus-depl.yaml
      - infra/k8s/ingress-srv.yaml
      - infra/k8s/moderation-depl.yaml
      - infra/k8s/posts-NodePort-srv.yaml
      - infra/k8s/posts-depl.yaml
      - infra/k8s/query-depl.yaml
