apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  namespace: dev-01
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: posts.com
      http:
        paths:
          - path: /posts/create
            backend:
              serviceName: posts-srv
              servicePort: 4000
          - path: /posts
            backend:
              serviceName: query-srv
              servicePort: 4002
          - path: /posts/?(.*)/comments
            backend:
              serviceName: comments-srv
              servicePort: 4001
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 80
#infra/k8s/ingress-srv.yaml

# 1. get react frontend
# GET http://posts.com  - client-srv 80

# 2. create a post
# POST http://posts.com/posts/create   -- posts-srv 4000

# 3. get posts
# GET http://posts.com/posts   - query-srv 4002

# 4. create a comment on a post
# POST http://posts.com/posts/b77d818f/comments  - comments-srv 4001
