apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
  namespace: dev-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: yinglu91/m-posts:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: posts-srv
  namespace: dev-01
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000

# kubectl delete ns dev-01    ---- at the beginning
# kubectl create ns dev-01
# $ kubectl apply -f .

# $ kubectl get pods -n dev-01
# NAME                               READY   STATUS    RESTARTS   AGE
# comments-depl-64574844f9-nlfpj     1/1     Running   0          62s
# event-bus-depl-797879c68d-mknqs    1/1     Running   0          27m
# moderation-depl-6748d48b45-6tf7n   1/1     Running   0          62s
# posts-depl-654f97d596-h5xzs        1/1     Running   0          27m
# query-depl-86f76db79c-b8frz        1/1     Running   0          62s

# YLu@USLT20149 MINGW64 /c/e-books/stephen/microservices/infra/k8s (master)
# $ kubectl get services -n dev-01
# NAME                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
# comments-srv          ClusterIP   10.111.173.232   <none>        4001/TCP         99s
# event-bus-srv         ClusterIP   10.109.5.61      <none>        4005/TCP         27m
# moderation-srv        ClusterIP   10.96.169.78     <none>        4003/TCP         99s
# posts-node-port-srv   NodePort    10.109.16.29     <none>        4000:32080/TCP   25m
# posts-srv             ClusterIP   10.107.139.225   <none>        4000/TCP         27m
# query-srv             ClusterIP   10.100.141.174   <none>        4002/TCP         99s

# if image changes e.g. event-bus one, 
# $ kubectl rollout restart deployment event-bus-depl -n dev-01
# deployment.apps/event-bus-depl restarted

# $ kubectl get pods -n dev-01
# NAME                               READY   STATUS    RESTARTS   AGE
# comments-depl-64574844f9-nlfpj     1/1     Running   0          10m
# event-bus-depl-769f9c95f8-mnrt8    1/1     Running   0          100s    +++++++
# moderation-depl-6748d48b45-6tf7n   1/1     Running   0          10m
# posts-depl-654f97d596-h5xzs        1/1     Running   0          37m
# query-depl-86f76db79c-b8frz        1/1     Running   0          10m

# $ kubectl logs -n dev-01 comments-depl-64574844f9-nlfpj

# > comments@1.0.0 serve
# > node index.js

# Listening on 4001
# Event Received: PostCreated

# $ kubectl logs -n dev-01 query-depl-86f76db79c-b8frz

# > query@1.0.0 serve
# > node index.js

# Listening on 4002
# Processing event: PostCreated

# $ kubectl logs -n dev-01 moderation-depl-64fff49bc7-9lb26

# > moderation@1.0.0 serve
# > node index.js

# Listening on 4003
# Received Event PostCreated

# extra k8s commands:
# $ kubectl get pods -n dev-01
# $ kubectl exec -it posts-depl-654f97d596-s2zw8 -n dev-01 -- sh
# $ kubectl logs posts-depl-654f97d596-s2zw8 -n dev-01
# $ kubectl describe -n dev-01 pod  posts-depl-654f97d596-s2zw8
# $ kubectl delete pod posts-depl-654f97d596-s2zw8 -n dev-01

# $ kubectl get services -n dev-01